parameters:
    almaviacx.default.syllabs.api.url: ~
    almaviacx.default.syllabs.config: []
services:
    # default configuration for services in *this* file
    _defaults:
        # automatically injects dependencies in your services
        autowire: true
        # automatically registers your services as commands, event subscribers, etc.
        autoconfigure: true
        # this means you cannot fetch services directly from the container via $container->get()
        # if you need to do this, you can override this setting on individual services
        public: false
        bind:
            $tagsService: '@eztags.api.service.tags'

    almaviacx.syllabs.api.httpclient.siteaccessaware:
        lazy: true
        class: AlmaviaCX\Syllabs\API\HttpClient
        decorates: AlmaviaCX\Syllabs\API\HttpClient
        arguments:
            $APIUrl: "$syllabs.api.url;almaviacx$"

    AlmaviaCX\Syllabs\Ez\Config\SyllabsConfiguration:

    AlmaviaCX\Syllabs\Ez\UI\Config\ConfigProvider:
        tags:
            - { name: ezplatform.admin_ui.config_provider, key: 'syllabs' }

    AlmaviaCX\Syllabs\Ez\Form\Extension\ContentEditTypeExtension:
        tags:
            - { name: form.type_extension, extended_type: EzSystems\RepositoryForms\Form\Type\Content\ContentEditType }

    AlmaviaCX\Syllabs\Ez\Service\SuggestionService:
        bind:
            $tagsService: '@eztags.api.service.tags.inner'
        arguments:
            $searchHandler: '@ezpublish.spi.search'
            $cache: '@ezpublish.cache_pool'
            $persistenceHandler: '@ezpublish.api.persistence_handler'

    AlmaviaCX\Bundle\Syllabs\EzBundle\Controller\ApiController: ~

    AlmaviaCX\Bundle\Syllabs\EzBundle\Command\CreateTagCommand: ~

